name: Update Homebrew Distribution

on:
  release:
    types: [published]

jobs:
  update-homebrew-distribution:
    name: Update Homebrew Tap and Create Official PR
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    
    steps:
      - name: Extract version and release info
        id: release_info
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "RELEASE_URL=${{ github.event.release.html_url }}" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=BOSS-${VERSION}-Universal.dmg" >> $GITHUB_OUTPUT
          echo "DOWNLOAD_URL=https://github.com/risa-labs-inc/BOSS-Releases/releases/download/v${VERSION}/BOSS-${VERSION}-Universal.dmg" >> $GITHUB_OUTPUT
          echo "📦 Processing BOSS release $VERSION"

      - name: Calculate SHA256 hash
        id: calculate_hash
        run: |
          # Download the DMG file to calculate SHA256
          echo "⬇️ Downloading DMG to calculate SHA256..."
          curl -fsSL -o "BOSS-${{ steps.release_info.outputs.VERSION }}-Universal.dmg" \
            "${{ steps.release_info.outputs.DOWNLOAD_URL }}"
          
          # Calculate SHA256
          SHA256=$(sha256sum "BOSS-${{ steps.release_info.outputs.VERSION }}-Universal.dmg" | cut -d' ' -f1)
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
          echo "🔒 Calculated SHA256: $SHA256"
          
          # Clean up downloaded file
          rm -f "BOSS-${{ steps.release_info.outputs.VERSION }}-Universal.dmg"

      - name: Update Homebrew Tap
        id: update_tap
        run: |
          echo "🍺 Updating custom Homebrew tap..."
          
          # Clone the tap repository
          git clone https://${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/risa-labs-inc/homebrew.git homebrew-tap
          cd homebrew-tap
          
          # Configure git
          git config user.name "BOSS Release Bot"
          git config user.email "noreply@risa-labs.com"
          
          # Update the cask file
          VERSION="${{ steps.release_info.outputs.VERSION }}"
          SHA256="${{ steps.calculate_hash.outputs.SHA256 }}"
          
          # Update version and SHA256 in boss.rb
          sed -i "s/version \"[^\"]*\"/version \"$VERSION\"/" Casks/boss.rb
          sed -i "s/sha256 \"[^\"]*\"/sha256 \"$SHA256\"/" Casks/boss.rb
          
          # Verify changes
          echo "📝 Updated cask file content:"
          head -10 Casks/boss.rb
          
          # Commit and push changes
          git add Casks/boss.rb
          git commit -m "🚀 Update BOSS to version $VERSION

          Release: ${{ steps.release_info.outputs.RELEASE_URL }}
          SHA256: $SHA256"
          
          # Push with retry logic
          for i in {1..3}; do
            if git push; then
              echo "✅ Successfully pushed to tap repository"
              echo "success=true" >> $GITHUB_OUTPUT
              break
            else
              echo "❌ Push attempt $i failed, retrying in 5 seconds..."
              sleep 5
              git pull --rebase
            fi
          done

      - name: Setup Homebrew for official PR
        if: steps.update_tap.outputs.success == 'true'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Create PR to official Homebrew
        if: steps.update_tap.outputs.success == 'true'
        id: create_pr
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_CASK_TOKEN }}
        run: |
          echo "🚀 Creating PR to official Homebrew repository..."
          
          # Use brew bump-cask-pr with proper hash
          if brew bump-cask-pr boss \
            --version="${{ steps.release_info.outputs.VERSION }}" \
            --sha256="${{ steps.calculate_hash.outputs.SHA256 }}" \
            --no-browse; then
            echo "✅ Successfully created PR to homebrew-cask"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to create PR to homebrew-cask"
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Notify completion
        if: always()
        run: |
          if [[ "${{ steps.update_tap.outputs.success }}" == "true" && "${{ steps.create_pr.outputs.success }}" == "true" ]]; then
            echo "✅ Successfully updated Homebrew distribution for BOSS ${{ steps.release_info.outputs.VERSION }}"
            echo "- Custom tap: Updated with SHA256 ${{ steps.calculate_hash.outputs.SHA256 }}"
            echo "- Homebrew cask: PR created successfully"
          else
            echo "❌ Failed to complete Homebrew distribution update"
            exit 1
          fi