name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    name: Update BOSS in Homebrew Tap
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    
    steps:
      - name: Extract version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Updating BOSS to version $VERSION"

      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: risa-labs-inc/homebrew
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update BOSS cask version
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          sed -i "s/version \"[^\"]*\"/version \"$VERSION\"/" Casks/boss.rb
          
          # Verify the change
          echo "📝 Updated cask file:"
          grep -A 2 "version" Casks/boss.rb
          
      - name: Commit and push changes
        run: |
          git config user.name "BOSS Release Bot"
          git config user.email "noreply@risa-labs.com"
          
          git add Casks/boss.rb
          git commit -m "🚀 Update BOSS to version ${{ steps.version.outputs.VERSION }}

          Release: ${{ github.event.release.html_url }}
          
          Co-authored-by: ${{ github.event.release.author.login }} <${{ github.event.release.author.id }}+${{ github.event.release.author.login }}@users.noreply.github.com>"
          
          git push